version: '3.8'

services:
  backend:
    build: ./backend
    container_name: presentation-backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - FLASK_DEBUG=False
      - PORT=5000
    volumes:
      - backend-data:/app/temp
    ports:
      - "8501:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    container_name: presentation-frontend
    environment:
      - REACT_APP_API_URL=https://api.apresentador.collos.com.br
    ports:
      - "7860:80"

volumes:
  backend-data: